import os
import re
import gzip

SRC_DIR = "src"

def minify_html(html: str) -> str:
    # Tags where whitespace should be preserved
    preserve_tags = ['pre', 'code', 'textarea', 'script', 'style']
    preserve_regex = '|'.join(preserve_tags)

    # Protect preserve blocks with placeholders
    preserve_blocks = []
    def preserve(match):
        preserve_blocks.append(match.group(0))
        return f"__PRESERVE_BLOCK_{len(preserve_blocks)-1}__"

    html = re.sub(rf'<({preserve_regex})[\s\S]*?</\1>', preserve, html, flags=re.IGNORECASE)

    # Remove HTML comments
    html = re.sub(r'<!--.*?-->', '', html, flags=re.DOTALL)

    # Collapse all whitespace between tags
    html = re.sub(r'>\s+<', '><', html)

    # Collapse multiple spaces inside tags
    html = re.sub(r'\s+', ' ', html)

    # Restore preserved blocks
    for i, block in enumerate(preserve_blocks):
        html = html.replace(f"__PRESERVE_BLOCK_{i}__", block)

    return html.strip()

def sanitize_identifier(name: str) -> str:
    """Sanitize a filename to create a valid C identifier.

    C identifiers must:
    - Start with a letter or underscore
    - Contain only letters, digits, and underscores
    """
    # Replace non-alphanumeric characters (including hyphens) with underscores
    sanitized = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    # Prefix with underscore if starts with a digit
    if sanitized and sanitized[0].isdigit():
        sanitized = f"_{sanitized}"
    return sanitized

for root, _, files in os.walk(SRC_DIR):
    for file in files:
        is_html = file.endswith(".html")
        is_js = file.endswith(".js")
        is_wasm = file.endswith(".wasm")
        if not (is_html or is_js or is_wasm):
            continue

        file_path = os.path.join(root, file)

        if is_wasm:
            # Binary asset: read raw bytes, no text decode / minify.
            with open(file_path, "rb") as f:
                raw = f.read()
            original_len = len(raw)
            processed_len = len(raw)
            compressed = gzip.compress(raw, compresslevel=9)
            suffix = "Wasm"
        else:
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()

            # Only minify HTML files; JS files are typically pre-minified (e.g., jszip.min.js)
            if is_html:
                processed = minify_html(content)
            else:
                processed = content

            original_len = len(content)
            processed_len = len(processed)
            # Compress with gzip (compresslevel 9 is maximum compression)
            # IMPORTANT: we don't use brotli because Firefox doesn't support brotli with insecured context (only supported on HTTPS)
            compressed = gzip.compress(processed.encode('utf-8'), compresslevel=9)
            suffix = "Html" if is_html else "Js"

        # Create valid C identifier from filename
        base_name = sanitize_identifier(f"{os.path.splitext(file)[0]}{suffix}")
        header_path = os.path.join(root, f"{base_name}.generated.h")

        with open(header_path, "w", encoding="utf-8") as h:
            h.write(f"// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
            h.write(f"#pragma once\n")
            h.write(f"#include <cstddef>\n\n")

            # Write the compressed data as a byte array
            h.write(f"constexpr char {base_name}[] PROGMEM = {{\n")

            # Write bytes in rows of 16
            for i in range(0, len(compressed), 16):
                chunk = compressed[i:i+16]
                hex_values = ', '.join(f'0x{b:02x}' for b in chunk)
                h.write(f"  {hex_values},\n")

            h.write(f"}};\n\n")
            h.write(f"constexpr size_t {base_name}CompressedSize = {len(compressed)};\n")
            h.write(f"constexpr size_t {base_name}OriginalSize = {processed_len};\n")

        print(f"Generated: {header_path}")
        print(f"  Original: {original_len} bytes")
        print(f"  Processed: {processed_len} bytes ({100*processed_len/original_len:.1f}%)")
        print(f"  Compressed: {len(compressed)} bytes ({100*len(compressed)/original_len:.1f}%)")
